# Generated by Django 3.2.6 on 2021-08-20 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_vu', models.IntegerField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compte.utilisateur')),
            ],
        ),
    ]
